### PR TITLE
Fix make gcc arm exporter

### PR DESCRIPTION
**Pull request by JojoS62**
## Description
Issue #3673
The make_gcc_arm exporter for mbed os 2 fails with linker errors for wrapper functions. These can be fixed by adding the libmbed.a to the linker group

## Status
**READY**

## Migrations
If this PR changes any APIs or behaviors, give a short description of what *API users* should do when this PR is merged.

NO

## Todos
- [ X] Tests
- [ ] Documentation

## Steps to test or reproduce
import mbed classic program
mbed export -i make_gcc_arm
make

will fail with messages like:
```
undefined` reference to `__wrap__free_r'
```

### CODE REVIEW

**Comment by theotherjimmy** [comment]
@JojoS62 Could you create the same PR to Armmbed/mbed-os#master?

**Comment by JojoS62** [comment]
@theotherjimmy I tried, but I always get many old commits included in the PR when I compare mbed-os/master with my branch.

**Comment by theotherjimmy** [comment]
I'm going to have a go at it then.

**Comment by JojoS62** [comment]
my workflow:
- cloned the mbed-os
- tried somethings in different branches
- when updates where availble, merged them into my master (using GitHub desktop)
- pushed the local copy to my origin
- then, when opening a PR, all the old stuff is in this PR

**Comment by theotherjimmy** [comment]
That's because of the mergeing, I think

This step:

>when updates where availble, merged them into my master (using GitHub desktop)

Could be: when updater are available, rebase my master to include them.

That way you would have exactly the same commits as master, with exactly the same hashes.

You could create a good branch from these commits by:
 1) checkout armmmbed/mbed-os master as a branch `git checkout origin master` then `git checkout -b fix-make-exporter`
 2) cherry-pick the commit that matter from this branch `git cherry-pick fix_make_GCC_ARM_exporter`

You should have one commit on top of armmbed/mbed-os and be ready for PR.

**Comment by JojoS62** [comment]
then the cherry-pick complains about not beeing a commit:

D:\Projects\Sn\LocalGit\mbed-os [fix-make-exporter]> git status
On branch fix-make-exporter
nothing to commit, working tree clean
D:\Projects\Sn\LocalGit\mbed-os [fix-make-exporter]> git diff
D:\Projects\Sn\LocalGit\mbed-os [fix-make-exporter]> git cherry-pick fix_make_GC
C_ARM_exporter
error: commit c20408e736ed50dd4812ee1181620e8b526bd5cc is a merge but no -m opti
on was given.
fatal: cherry-pick failed
D:\Projects\Sn\LocalGit\mbed-os [fix-make-exporter]>

**Comment by JojoS62** [comment]
ok, with this link I got the commit number  c20408e  for the cherry-pick

**Comment by JojoS62** [comment]
https://github.com/ARMmbed/mbed-os/compare/master...JojoS62:fix-make-exporter

includes again all stuff, driving me nuts

**Comment by theotherjimmy** [comment]
Sorry, I assumed that you would have armmbed/mbed-os as origin.

You just need commit `3f14630d813d2d09ad14e889bde9d703ceb1d64f`, so checkout armmbed/mbed-os master as a branch and then `git cherry-pick 3f14630d813d2d09ad14e889bde9d703ceb1d64f`

**Comment by JojoS62** [comment]
very close:

D:\Projects\Sn\LocalGit\mbed-os [armmbed/master]> git checkout ARMmbed/master
Your branch is up-to-date with 'remotes/ARMmbed/master'.
warning: refname 'ARMmbed/master' is ambiguous.
Switched to branch 'ARMmbed/master'
D:\Projects\Sn\LocalGit\mbed-os [ARMmbed/master =]> git cherry-pick 3f14630d813d
2d09ad14e889bde9d703ceb1d64f
[ARMmbed/master d76a10644] Fix for unresolved linker errors
 Date: Wed Jul 26 23:20:21 2017 +0200
 2 files changed, 2 insertions(+), 2 deletions(-)
D:\Projects\Sn\LocalGit\mbed-os [ARMmbed/master ↑1]> git push origin
fatal: You are pushing to remote 'origin', which is not the upstream of
your current branch 'ARMmbed/master', without telling me what to push
to update which remote branch.
D:\Projects\Sn\LocalGit\mbed-os [ARMmbed/master ↑1]>

**Comment by JojoS62** [comment]
I cannot push this to armmbed, and the compare armmbe-my branch shows again all commits. I think have to clone a clean mbed-os, this takes some time, I'll be back later.

**Comment by theotherjimmy** [comment]
@JojoS62 Push to your fork, then compare across forks.

**Pull request merged**
